import type { Metadata, Viewport } from "next";
import "@fontsource/encode-sans-semi-condensed/400.css";
import "@fontsource/encode-sans-semi-condensed/500.css";
import "@fontsource/encode-sans-semi-condensed/600.css";
import "@fontsource/encode-sans-semi-condensed/700.css";
import "@fontsource/encode-sans-semi-condensed/900.css";
import { RouteProvider } from "@/providers/router-provider";
import "@/styles/globals.css";

export const metadata: Metadata = {
    title: "Starter kit — Untitled UI",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#11224d",
    colorScheme: "light dark",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="de" className="light-mode">
            <body className="bg-primary antialiased">
                <RouteProvider>
                    {children}
                </RouteProvider>
            </body>
        </html>
    );
}
